### ISSUE TITLE
Add Google Container Registry to Portainer on deploy

### ISSUE THREAD

**Issue by marioacarvalho** [christippett/terraform-cloudinit-container-server#13]
Hello, trying to do this for some days.

On the cloud_config.yaml, after 

`systemctl daemon-reload && systemctl enable --now app app-monitor.path`

I added 

`docker login -u oauth2accesstoken -p TOKEN https://gcr.io`

but it doesn't appear on the Portainer Registry UI. I want to automate the deployment of a custom docker image stored on GCR..

Any idea?

**Comment by christippett** [comment]
I’m not too familiar with Portainer and I’m not sure if authenticating the registry with Docker also means it’s available to Portainer.

Have you tried including a custom config for Portainer with the registry details?

**Comment by marioacarvalho** [comment]
It can be done using the [Portainer API](https://docs.portainer.io/v/ce-2.9/api/docs). But for now I just made the image public and after the Docker Pull I set it back to private. 

Thank you. Congrats on the project
