### ISSUE TITLE
Volume mount

### ISSUE THREAD

**Issue by chellem** [christippett/terraform-cloudinit-container-server#15]
Hello, 

I want to know if it's possible to mount files/directory ?

Regards,

**Comment by christippett** [comment]
Hey. Sorry for the very long wait for a reply!

Yep, it's possible to mount a drive or directory - whatever you want really. One of the Google Cloud examples [here](https://github.com/christippett/terraform-cloudinit-container-server/blob/62d3b51c21935ec5d2a73bc238ad5efb011ab26a/examples/gcp-docker-compose-advanced/main.tf#L32-L42) demonstrates this by initialising and mounting a drive to be used by the machine.

You can configure things by using whatever shell commands you'd normally run, or leverage one of the cloud-init templates that manages the setup for you (see their `mount` module [here](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#mounts)). The benefit of the latter is that it's designed to work across all distributions supported by cloud-init.

```terraform
module "container-server" {
  source = "christippett/container-server/cloudinit"

  domain = "example.com"
  email  = "me@example.com"

  files = [
    {
      filename = "docker-compose.yaml"
      content  = filebase64("${path.module}/docker-compose.yaml")
    }
  ]
  env = {
    KEY = "value"
  }

  # additional cloud-init steps (defined here as a yaml string)
  cloudinit_part = [{
    content_type = "text/cloud-config"
    content      = <<EOT
#cloud-config
mounts:
    - ["ephemeral0", "/mnt", "auto","defaults,nofail,x-systemd.requires=cloud-init.service", "0", "2"]
    - ["swap", "none", "swap", "sw", "0", "0"]
EOT
  }]
}

```

Add your extra cloud-init steps/config to the `cloudinit_part` variable and it'll execute the required steps as part of the server setup.
