### ISSUE TITLE
Docker not found

### ISSUE THREAD

**Issue by crisp2u** [christippett/terraform-cloudinit-container-server#6]
Hi, I just started playing with this and noticed a couple of errors. It seems docker is not installed by the default cloudinit template. Further more if I install it with an extra cloudinit part config I get another error `-bash: /run/app/.bin/docker-compose: Permission denied` 

Is this thing working or it needs more work ?

Thanks

**Comment by christippett** [comment]
Hey @crisp2u,

The module assumes Docker is already installed on the base OS. Installing it via an extra cloudinit template sounds like a good workaround in theory, however any additional configs end up being *appended* to the default config, meaning you'll likely run into issues with Docker being unavailable (which is why you're here!).

One of the `runcmd` steps in the default config is to create a new Docker network. This step occurs before `docker-compose` is installed, so if it fails (which it will, if Docker isn't available), then Docker Compose will never install and you'll run into the error you're experiencing. That's my take of the situation at least...

Can you provide the OS + version you're using, cloud provider and the Terraform module version?

Any chance you can start with an OS image that has Docker pre-installed?

**Comment by crisp2u** [comment]
I'll come back with the details later, i managed to install docker using `package` but the downloaded copy of compose does not run, i get `Permission denied`

**Comment by christippett** [comment]
Where and when are you getting the permission error? Docker Compose is installed as `root`, so you'll need to have elevated privileges to run it (are you trying to run it from an interactive shell?). Normally it'd run from `systemd`, so `root` privileges aren't an issue.

**Comment by crisp2u** [comment]
OS: ubuntu 18.04
Platform: AWS EC2 t2.micro instance
Module version: is configured like in the example, version = "~> 1.1"
```
data "template_file" "boot" {
  template = file("${path.module}/init.tpl")
  vars = {
  }
}

module "container-server" {
  source  = "christippett/container-server/cloudinit"
  version = "~> 1.1"

  domain = "example.com"
  email  = "ops@example.com"

  container = {
    image   = "nginxdemos/hello"
  }
  cloudinit_part = [
    {
      filename     = "init.cfg"
      content_type = "text/cloud-config"
      content      = data.template_file.boot.rendered
  }
  ]
}
```

the extra part file is 
```
#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
# Note: Content strings here are truncated for example purposes.
#package_update: true
#package_upgrade: true
packages:
  - docker.io
  - docker-compose
```
This fixes the initial error about docker not installed. 
After ssh-ing into the instance:

`systemctl status app.service`

```
● app.service - Docker Compose Service (app)
   Loaded: loaded (/etc/systemd/system/app.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-09-01 15:35:43 UTC; 4min 44s ago
  Process: 4369 ExecStopPost=/run/app/.bin/docker-compose -f docker-compose.app.yaml rm -f (code=exited, status=203/EXEC)
  Process: 4363 ExecStart=/run/app/.bin/docker-compose -f docker-compose.app.yaml up (code=exited, status=203/EXEC)
  Process: 4361 ExecStartPre=/run/app/.bin/docker-compose -f docker-compose.app.yaml rm -f (code=exited, status=203/EXEC)
 Main PID: 4363 (code=exited, status=203/EXEC)

Sep 01 15:35:43 ip-172-31-45-233 systemd[1]: Starting Docker Compose Service (app)...
Sep 01 15:35:43 ip-172-31-45-233 systemd[4361]: app.service: Failed to execute command: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[4361]: app.service: Failed at step EXEC spawning /run/app/.bin/docker-compose: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[1]: Started Docker Compose Service (app).
Sep 01 15:35:43 ip-172-31-45-233 systemd[4363]: app.service: Failed to execute command: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[4363]: app.service: Failed at step EXEC spawning /run/app/.bin/docker-compose: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[1]: app.service: Main process exited, code=exited, status=203/EXEC
Sep 01 15:35:43 ip-172-31-45-233 systemd[4369]: app.service: Failed to execute command: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[4369]: app.service: Failed at step EXEC spawning /run/app/.bin/docker-compose: Permission denied
Sep 01 15:35:43 ip-172-31-45-233 systemd[1]: app.service: Failed with result 'exit-code'.
```

`ls -la /run/app/.bin/`

```
total 11972
drwxr-xr-x 2 root root       60 Sep  1 15:35 .
drwxr-xr-x 4 root root      160 Sep  1 15:35 ..
-rwxr-xr-x 1 root root 12255808 Sep  1 15:35 docker-compose
```

**Comment by christippett** [comment]
Can you try run the following and see if it works?

```bash
sudo TMP=/run/app/.tmp /run/app/.bin/docker-compose --help
```

**Comment by crisp2u** [comment]
`sudo TMP=/run/app/.tmp /run/app/.bin/docker-compose --help`
same
```sudo: unable to execute /run/app/.bin/docker-compose: Permission denied```

but the one installed from package works `/usr/bin/docker-compose --help`

**Comment by crisp2u** [comment]
The version downloaded from the registry is 1.1.0

**Comment by christippett** [comment]
I've run out ideas @crisp2u. When I get a chance this over the next few days I'll spin up an ec2 instance of my own to see if I can replicate the issue. Would you mind sharing the Terraform script(s) you've been using?

**Comment by crisp2u** [comment]
Hi @christippett. So I've managed to run this by copying local the v1.1 code from github and removing the `./bin/docker-compose` and use `/usr/bin/docker-compose`. The simplified/redacted code is 
```
#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
# Note: Content strings here are truncated for example purposes.
#package_update: true
#package_upgrade: true
packages:
  - gnupg2
  - pass
  - awscli
  - docker.io
  - docker-compose

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

```
```
data "aws_ami" "ubuntu1804" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"]

  provider = aws.sectorlabs

}
data "template_file" "boot" {
  template = file("${path.module}/init.tpl")
}

module "container-server" {
  source  = "christippett/container-server/cloudinit"
  version = "~> 1.1"

  domain = "example.com"
  email  = "ops@example.com"
  container = {
    image   = "nginxdemos/hello"
  }
  cloudinit_part = [
    {
      filename     = "init.cfg"
      content_type = "text/cloud-config"
      content      = data.template_file.boot.rendered
  }
  ]

  l
resource "aws_instance" "this" {
  ami                    = data.aws_ami.ubuntu1804.id
  instance_type          = local.instance_type
  subnet_id              = local.subnet_id
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.app-sg.id, aws_security_group.ssh-sg.id]

  root_block_device {
    delete_on_termination = false
    volume_size           = 10
  }

  user_data = module.container-server.cloud_config


  associate_public_ip_address = true

}
```

I don't know how to trace the root cause of the permission denied error, maybe with strace.

Also, any suggestions how to run `docker login` to pull from private repo before the start of the container ? adding another cloudinit part with `runcmd` is too late 

Thanks

**Comment by boscard** [comment]
Problem with permission denied is because most of Linux distributions set `noexec` flag on `/run` directory for security reasons:
```
admin@ip-172-31-82-144:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=496796k,nr_inodes=124199,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=101124k,mode=755)
...
```

**Comment by boscard** [comment]
I've created PR which should fix this issue. Tested on Debian 10.
